---
# tasks file for postgresql

- name: Criando usuario de banco no PostgreSQL para aplicacao Stoq
  postgresql_user: name=stoq 
  become: yes
  become_user: postgres

- name: Criando banco de dados para aplicacao Stoq
  postgresql_db: name={{db_name}}
  become: yes
  become_user: postgres

- name: Cadastrando senha do usuario stoq e atribuindo privilegio de acesso 
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}} priv=ALL
  become: yes
  become_user: postgres



