---
# tasks file for server

- name: Atualizando cache do servidor
  apt: update_cache=yes cache_valid_time=3600

- name: Instalando os pacotes necessarios
  apt: name={{ item }} state=present
  with_items:
  - python-psycopg2
  - stoq
  - postgresql-9.5
  
